# Generated by Django 4.2.5 on 2023-09-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('programa', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('emailInstitucional', models.CharField(max_length=80)),
                ('emailPersonal', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('fechaRegistro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
